pub mod activity;
pub mod ai_agent;
pub mod arcade;
pub mod category;
pub mod chat;
pub mod collection;
pub mod comment;
pub mod feedback;
pub mod game;
pub mod gamification;
pub mod interaction;
pub mod news;
pub mod news_category;
pub mod notification;
pub mod prefs;
pub mod quests;
pub mod referral;
pub mod repo_repo;
pub mod report;
pub mod review;
pub mod rps;
pub mod session;
pub mod settings_repo;
pub mod shop;
pub mod tag;
pub mod user;
pub mod word_chain;

pub use activity::ActivityRepo;
pub use ai_agent::AiAgentRepo;
pub use arcade::{SpinRepo, TriviaRepo};
pub use category::CategoryRepo;
pub use chat::ChatRepo;
pub use collection::{CollectionRepo, ViewHistoryRepo};
pub use comment::CommentRepo;
pub use feedback::FeedbackRepo;
pub use game::GameRepo;
pub use gamification::GamificationRepo;
pub use interaction::InteractionRepo;
pub use news::NewsRepo;
pub use news_category::NewsCategoryRepo;
pub use notification::NotificationRepo;
pub use prefs::PrefsRepo;
pub use quests::{OnboardingRepo, QuestRepo};
pub use referral::ReferralRepo;
pub use repo_repo::RepoRepo;
pub use report::ReportRepo;
pub use review::ReviewRepo;
pub use rps::RpsRepo;
pub use session::SessionRepo;
pub use settings_repo::{AdminLogRepo, SettingsRepo, StatsRepo};
pub use shop::ShopRepo;
pub use tag::TagRepo;
pub use user::UserRepo;
pub use word_chain::WordChainRepo;
